spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/sist_distribuidos_dib
    username: postgres
    password: 1234
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect

server:
  port: 8081